### PR TITLE
Add some files adapted from amrex.

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Review by asalmgren — COMMENTED** [review]
I really like the new version of CONTRIBUTING.md!  Two places I would add clarification.  1) Does it matter which branch you're currently in when you type line 136?  If you do that while in your separate branch, doesn't it just update development branch and not your branch_name?  Or does branch_name also try to update when you pull development?    2) line 231 -- maybe start that sentence with "When declaring a function..."?

**Comment by WeiqunZhang** [comment]
Updated.

**Review by asalmgren — COMMENTED** [review]
I think line 136 should be AMReX-Hydro not amrex ... otherwise looks good

**Review by asalmgren — APPROVED** [review]

**Comment by WeiqunZhang** [comment]
> I think line 136 should be AMReX-Hydro not amrex ... otherwise looks good

Thanks for catching this!

**Pull request merged**
